### ISSUE TITLE
[DOCUMENTATION] Add and modify current Javadoc

### ISSUE THREAD

**Issue by MarineB210** [MarineB210/calculator-cucumber-2024#25]
** Issue **
The current Javadoc is wrong and some part of the codes are not documented.

** Classification **
Improvement and addition of documentation

**Comment by MarineB210** [comment]
I wrote some Javadoc for my personal extension (Boolean algebra)

**Comment by SamuelSVG** [comment]
Javadoc is now complete for the common calculator and the time operations extension
